name: borneo-pra
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - pandas
  - openpyxl<=3.1.0
  - seaborn
  - matplotlib
  - plotly
  - rpy2
  - ipykernel
  - ipywidgets
  - jupyter
